# Helix configuration
# Gruvbox theme is set as the default

theme = "gruvbox"

[keys.normal.space]
q = ":quit"
Q = ":quit!"
s = ":write"
"=" = ":format"
c = ":bc"
C = ":bca"
x = ":bc"
# Add comma to the end of the line
"," = [
    "save_selection",
    "goto_line_end",
    ":append-output printf ','",
    "jump_backward",
]
# Add semicolon to the end of the line
";" = [
    "save_selection",
    "goto_line_end",
    ":append-output printf ';'",
    "jump_backward",
]

[editor]
line-number = "relative"
true-color = true
undercurl = true
color-modes = true
cursorline = true
auto-save = true # save when window looses focus
auto-completion =true
idle-timeout = 0
# original gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
gutters = ["diagnostics", "spacer", "diff", "line-numbers", "spacer", "spacer"]
indent-heuristic = "tree-sitter"

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true
# display-inlay-hints = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
right = ["diagnostics", "version-control", "position", "file-encoding"]

[editor.indent-guides]
render = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "all"

[editor.whitespace.characters]
tab = "→"
[editor.soft-wrap]
enable = true

  
[keys.normal]
esc = ["collapse_selection", "keep_primary_selection", ":w"] # remove additional cursors and selections
# 
# "\\" is how to use \ as the beginning of a mapping,
# and so this is a subtable of keys.normal for \
[keys.normal."\\"]
c = ":bc"
g = "goto_file"
