general {
  lock_cmd = $HOME/dotfiles/scripts/idle-guard.sh lock
  before_sleep_cmd = loginctl lock-session
  after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
  timeout = 300
  on-timeout = $HOME/dotfiles/scripts/idle-guard.sh dpms
  on-resume = hyprctl dispatch dpms on
}

listener {
  timeout = 600
  on-timeout = $HOME/dotfiles/scripts/idle-guard.sh lock
}
