#!/usr/bin/env bash
#
# theme-switch.sh — Switch between color schemes system-wide
# Uses gum for interactive selection when run without args.
#
# Usage:
#   theme-switch.sh                        # gum TUI
#   theme-switch.sh catppuccin mocha
#   theme-switch.sh catppuccin macchiato
#   theme-switch.sh gruvbox dark
#   theme-switch.sh gruvbox light
#   theme-switch.sh solarized dark
#   theme-switch.sh solarized light
#   theme-switch.sh next                   # cycle through all themes
#
set -euo pipefail

DOTFILES="${DOTFILES:-$HOME/dotfiles}"
THEMES_DIR="$DOTFILES/themes"
DRY_RUN=false

# ── Ensure gum ────────────────────────────────────────────────────
if ! command -v gum &>/dev/null; then
  echo "Installing gum..."
  curl -fsSL https://github.com/charmbracelet/gum/releases/latest/download/gum_amd64.deb \
    -o /tmp/gum.deb && sudo dpkg -i /tmp/gum.deb && rm /tmp/gum.deb
fi

# ── Helpers ───────────────────────────────────────────────────────
header()  { gum style --border thick --padding "1 2" --margin "0 0 1 0" "$1"; }
ok()      { gum style --foreground 42 "  ✓ $1"; }
warn()    { gum style --foreground 220 "  ! $1"; }

# ── Theme list ─────────────────────────────────────────────────────
declare -A THEMES
THEMES["catppuccin mocha"]="catppuccin-mocha.sh"
THEMES["catppuccin macchiato"]="catppuccin-macchiato.sh"
THEMES["gruvbox dark"]="gruvbox-dark.sh"
THEMES["gruvbox light"]="gruvbox-light.sh"
THEMES["solarized dark"]="solarized-dark.sh"
THEMES["solarized light"]="solarized-light.sh"

THEME_ORDER=(
  "catppuccin mocha"
  "catppuccin macchiato"
  "gruvbox dark"
  "gruvbox light"
  "solarized dark"
  "solarized light"
)

# ── Resolve theme ─────────────────────────────────────────────────
resolve_theme() {
  local theme="$1"
  local variant="${2:-}"
  local key

  if [[ -n "$variant" ]]; then
    key="$theme $variant"
    [[ -n "${THEMES[$key]:-}" ]] && { echo "$key"; return; }
  fi

  # Default variant per family
  case "$theme" in
    catppuccin) echo "catppuccin mocha"; return ;;
    gruvbox)    echo "gruvbox dark";    return ;;
    solarized)  echo "solarized dark";  return ;;
  esac

  echo ""
}

# ── Source palette ────────────────────────────────────────────────
load_palette() {
  local key="$1"
  local file="${THEMES[$key]}"
  source "$THEMES_DIR/$file"
}

# ── Write generated files ──────────────────────────────────────────

wc() {
  local f="$1"
  if $DRY_RUN; then
    gum style --foreground 33 "  ~ would write $f"
    if [[ -t 0 ]]; then return; fi
    local line
    while IFS= read -r line; do
      gum style --foreground 33 "    $line"
    done
    return
  fi
  mkdir -p "$(dirname "$f")"
  cat > "$f"
}

write_hypr_colors() {
  local f="$HOME/.config/hypr/colors.conf"
  wc "$f" <<EOF
# Hyprland colors — generated by theme-switch.sh
\$border_active   = rgba($(strip_hash $TH_BORDER_ACTIVE)ee)
\$border_inactive = rgba($(strip_hash $TH_BORDER_INACTIVE)ee)
EOF
  $DRY_RUN || ok "hypr colors → $f"
}

write_waybar_colors() {
  local dir="$HOME/.config/waybar"
  wc "$dir/colors.css" <<EOF
/* waybar colors — generated by theme-switch.sh */
@define-color bg      #$(strip_hash $TH_BG);
@define-color fg      #$(strip_hash $TH_FG);
@define-color accent  #$(strip_hash $TH_ACCENT);
@define-color surface #$(strip_hash $TH_SURFACE);
@define-color overlay #$(strip_hash $TH_OVERLAY);
@define-color green   #$(strip_hash $TH_GREEN);
@define-color red     #$(strip_hash $TH_RED);
@define-color yellow  #$(strip_hash $TH_YELLOW);
@define-color blue    #$(strip_hash $TH_BLUE);
@define-color magenta #$(strip_hash $TH_MAGENTA);
@define-color cyan    #$(strip_hash $TH_CYAN);
EOF
  $DRY_RUN || ok "waybar colors → $dir/colors.css"
  # Create base style.css if it doesn't exist
  if [[ ! -f "$dir/style.css" ]]; then
    wc "$dir/style.css" <<'CSS'
@import "colors.css";
* { font-family: "JetBrains Mono Nerd Font", sans-serif; font-size: 13px; }
window#waybar { background: @bg; color: @fg; }
#workspaces button { background: @surface; color: @fg; border-radius: 4px; margin: 2px; }
#workspaces button.active { background: @accent; color: @bg; }
#clock, #network, #bluetooth, #pulseaudio, #battery, #tray { padding: 0 8px; }
#clock { color: @accent; }
#network { color: @green; }
#pulseaudio { color: @cyan; }
#battery { color: @green; }
#battery.critical { color: @red; }
CSS
  fi
}

write_swaync_colors() {
  local dir="$HOME/.config/swaync"
  wc "$dir/colors.css" <<EOF
/* swaync colors — generated by theme-switch.sh */
@define-color bg      #$(strip_hash $TH_BG);
@define-color fg      #$(strip_hash $TH_FG);
@define-color accent  #$(strip_hash $TH_ACCENT);
@define-color surface #$(strip_hash $TH_SURFACE);
@define-color overlay #$(strip_hash $TH_OVERLAY);
EOF
  $DRY_RUN || ok "swaync colors → $dir/colors.css"
  if [[ ! -f "$dir/style.css" ]]; then
    wc "$dir/style.css" <<'CSS'
@import "colors.css";
* { all: unset; font-family: "JetBrains Mono Nerd Font", sans-serif; font-size: 13px; }
.notification-row { outline: none; }
.notification { background: @bg; border: 1px solid @surface; border-radius: 8px; margin: 4px; }
.notification-content { background: @bg; padding: 8px; }
.title { color: @fg; font-weight: bold; }
.summary { color: @fg; }
.body { color: @overlay; }
.control-center { background: @bg; border: 1px solid @surface; border-radius: 8px; }
.control-center-dnd { color: @accent; }
.widget-title { color: @fg; }
.widget-label { color: @fg; }
CSS
  fi
}

write_kitty_theme() {
  local f="$HOME/.config/kitty/current-theme.conf"

  local fg_bright="${TH_WHITE:-$TH_FG}"
  local bg_bright="${TH_SURFACE:-$TH_BG}"

  wc "$f" <<KITTY
# Kitty theme — generated by theme-switch.sh
# Theme: ${TH_NAME:-unknown}
foreground              $TH_FG
background              $TH_BG
selection_foreground    $TH_BG
selection_background    $TH_ACCENT
cursor                  $TH_ACCENT
cursor_text_color       $TH_BG
active_border_color     $TH_BORDER_ACTIVE
inactive_border_color   $TH_BORDER_INACTIVE
active_tab_foreground   $TH_BG
active_tab_background   $TH_ACCENT
inactive_tab_foreground $TH_FG
inactive_tab_background $TH_SURFACE
tab_bar_background      $TH_BG
color0 $TH_SURFACE
color8 $TH_OVERLAY
color1 $TH_RED
color9 $TH_RED
color2 $TH_GREEN
color10 $TH_GREEN
color3 $TH_YELLOW
color11 $TH_YELLOW
color4 $TH_BLUE
color12 $TH_BLUE
color5 $TH_MAGENTA
color13 $TH_MAGENTA
color6 $TH_CYAN
color14 $TH_CYAN
color7 $TH_FG
color15 $TH_SUBTEXT
KITTY
  $DRY_RUN || ok "kitty theme → $f"
}

write_rofi_colors() {
  local f="$HOME/.config/rofi/colors.rasi"
  wc "$f" <<RASI
/* rofi colors — generated by theme-switch.sh */
* {
    foreground:    #$(strip_hash $TH_FG);
    background-color: #$(strip_hash $TH_BG);
    active-background: #$(strip_hash $TH_ACCENT);
    urgent-background: #$(strip_hash $TH_RED);
    urgent-foreground: #$(strip_hash $TH_BG);
    selected-background: #$(strip_hash $TH_ACCENT);
    separatorcolor: #$(strip_hash $TH_ACCENT);
    bordercolor:    #$(strip_hash $TH_ACCENT);
}
RASI
  $DRY_RUN || ok "rofi colors → $f"

  # Ensure config.rasi imports colors.rasi
  local rc="$HOME/.config/rofi/config.rasi"
  if [[ -f "$rc" ]]; then
    if ! grep -qs '@import "colors.rasi"' "$rc"; then
      sed -i "/@import \"colors.rasi\"/d" "$rc"
      # Insert after the closing } of the * block
      awk '/^\* \{/,/^\}/ { if (/^\}/) { print; print "@import \"colors.rasi\""; next } }1' "$rc" > "${rc}.tmp"
      mv "${rc}.tmp" "$rc"
      ok "added @import to rofi/config.rasi"
    fi
  fi
}

dry() {
  if $DRY_RUN; then gum style --foreground 33 "  ~ $*"; else "$@"; fi
}

strip_hash() {
  echo "$1" | sed 's/^#//'
}

# ── Apply system-wide ──────────────────────────────────────────────

install_gtk_theme() {
  local theme="$1"
  local theme_dir="${XDG_DATA_HOME:-$HOME/.local/share}/themes"

  # Catppuccin GTK (official GitHub releases)
  if echo "$theme" | grep -qi "catppuccin"; then
    local flavor accent
    flavor=$(echo "$theme" | sed -E 's/Catppuccin-([A-Za-z]+).*/\1/' | tr '[:upper:]' '[:lower:]')
    accent=$(echo "$theme" | sed -E 's/.*-([A-Za-z]+)-(Dark|Light)$/\1/' | tr '[:upper:]' '[:lower:]')
    [[ -z "$accent" || "$accent" == "$flavor" ]] && accent="blue"
    local zip_name="catppuccin-${flavor}-${accent}-standard+default.zip"
    local url="https://github.com/catppuccin/gtk/releases/latest/download/${zip_name}"
    local tmp; tmp=$(mktemp -d)
    if curl -fsSL "$url" -o "$tmp/theme.zip"; then
      unzip -qo "$tmp/theme.zip" -d "$tmp/extracted"
      mkdir -p "$theme_dir"
      cp -r "$tmp/extracted"/* "$theme_dir/"
      ok "installed GTK theme: $theme"
    else
      warn "failed to download: $url"
    fi
    rm -rf "$tmp"
    return
  fi

  # For non-Catppuccin themes, just warn and try gsettings anyway
  warn "GTK theme '$theme' not installed (install manually: $theme_dir/)"
}

set_gtk_theme() {
  local theme="${TH_GTK:-}"
  [[ -z "$theme" ]] && return
  if $DRY_RUN; then echo "  ~ would set GTK theme: $theme"; return; fi

  # Check if installed
  local theme_dir="${XDG_DATA_HOME:-$HOME/.local/share}/themes"
  local usr_theme_dir="/usr/share/themes"
  if [[ ! -d "$theme_dir/$theme" && ! -d "$usr_theme_dir/$theme" ]]; then
    if [[ -t 0 ]] && command -v gum &>/dev/null; then
      if gum confirm "GTK theme '$theme' not found. Install it?"; then
        install_gtk_theme "$theme"
      fi
    else
      warn "GTK theme '$theme' not found, skipping installation (non-interactive)"
    fi
  fi

  if command -v gsettings &>/dev/null; then
    gsettings set org.gnome.desktop.interface gtk-theme "$theme" 2>/dev/null || \
      warn "failed to set GTK theme (check that '$theme' is installed)"
    gsettings set org.gnome.desktop.interface color-scheme "prefer-dark" 2>/dev/null || true
    ok "GTK theme → $theme"
  fi
}

set_wallpaper() {
  local wall="${TH_WALL:-}"
  [[ -z "$wall" ]] && return
  if $DRY_RUN; then echo "  ~ would set wallpaper: $wall"; return; fi
  local path="$DOTFILES/assets/$wall"
  if [[ -f "$path" ]] && command -v hyprctl &>/dev/null; then
    hyprctl hyprpaper wallpaper ",$path" 2>/dev/null || true
    ok "wallpaper → $wall"
  elif [[ ! -f "$path" ]]; then
    warn "wallpaper not found: $path"
  fi
}

reload_services() {
  if $DRY_RUN; then echo "  ~ would reload services (hyprland, waybar, swaync)"; return; fi
  # Hyprland
  if command -v hyprctl &>/dev/null; then
    hyprctl reload 2>/dev/null && ok "hyprland reloaded" || true
  fi
  # Waybar
  pkill -SIGUSR2 waybar 2>/dev/null || true
  # swaync
  if command -v swaync-client &>/dev/null; then
    swaync-client -rs 2>/dev/null || true
  fi
  ok "services reloaded"
}

# ══════════════════════════════════════════════════════════════════
#  Main
# ══════════════════════════════════════════════════════════════════

# ── Parse flags ──────────────────────────────────────────────────
PASSTHROUGH=()
FLAGS_DONE=false
THEME_KEY=""

for arg in "$@"; do
  if $FLAGS_DONE; then PASSTHROUGH+=("$arg"); continue; fi
  case "$arg" in
    --dry-run|-n) DRY_RUN=true ;;
    --list|-l)
      echo "Available themes:"
      for t in "${THEME_ORDER[@]}"; do echo "  $t ($(source "$THEMES_DIR/${THEMES[$t]}" 2>/dev/null && echo "$TH_NAME"))"; done
      exit 0 ;;
    --) FLAGS_DONE=true ;;
    *) PASSTHROUGH+=("$arg"); FLAGS_DONE=true ;;
  esac
done

set -- "${PASSTHROUGH[@]}"

# ── Resolve which theme to apply ──────────────────────────────────
if [[ $# -eq 0 ]]; then
  # Interactive: pick theme family then variant
  if $DRY_RUN; then
    header "🎨 Dry Run — interactive skipped, would prompt for theme family"
    echo "Available: catppuccin, gruvbox, solarized"
    echo "Use: theme-switch [--dry-run] <family> <variant>"
    exit 0
  fi
  header "🎨 Theme Switcher"
  FAMILY=$(printf "catppuccin\ngruvbox\nsolarized" | gum choose --header "Pick a theme family:" --cursor "➜ ")
  case "$FAMILY" in
    catppuccin)
      VARIANT=$(printf "mocha\nmacchiato" | gum choose --header "Catppuccin variant:" --cursor "➜ ")
      THEME_KEY="catppuccin $VARIANT"
      ;;
    gruvbox)
      VARIANT=$(printf "dark\nlight" | gum choose --header "Gruvbox variant:" --cursor "➜ ")
      THEME_KEY="gruvbox $VARIANT"
      ;;
    solarized)
      VARIANT=$(printf "dark\nlight" | gum choose --header "Solarized variant:" --cursor "➜ ")
      THEME_KEY="solarized $VARIANT"
      ;;
  esac
elif [[ "$1" == "next" ]]; then
  # Cycle to next theme
  CURRENT_THEME=""
  if [[ -f "$HOME/.cache/theme-switch-current" ]]; then
    CURRENT_THEME=$(cat "$HOME/.cache/theme-switch-current")
  fi
  FOUND=false
  for t in "${THEME_ORDER[@]}"; do
    if $FOUND; then THEME_KEY="$t"; break; fi
    [[ "$t" == "$CURRENT_THEME" ]] && FOUND=true
  done
  THEME_KEY="${THEME_KEY:-${THEME_ORDER[0]}}"
else
  THEME_KEY=$(resolve_theme "$1" "${2:-}")
fi

if [[ -z "$THEME_KEY" || -z "${THEMES[$THEME_KEY]:-}" ]]; then
  warn "Unknown theme. Available:"
  for t in "${!THEMES[@]}"; do echo "  $t"; done
  exit 1
fi

# Self-install: ensure available in PATH as 'theme-switch'
if [[ ! -L "$HOME/.local/bin/theme-switch" ]]; then
  mkdir -p "$HOME/.local/bin"
  ln -sf "$DOTFILES/scripts/theme-switch.sh" "$HOME/.local/bin/theme-switch"
fi

header "🎨 $THEME_KEY"

# ── Load palette ──────────────────────────────────────────────────
load_palette "$THEME_KEY"

# ── Write colors for each app ─────────────────────────────────────
write_hypr_colors
write_waybar_colors
write_swaync_colors
write_kitty_theme
write_rofi_colors

# ── Apply system theming ──────────────────────────────────────────
set_gtk_theme
set_wallpaper

# ── Reload services ───────────────────────────────────────────────
reload_services

# ── Save current theme for 'next' cycle ───────────────────────────
if $DRY_RUN; then
  echo "  ~ would save current theme → ~/.cache/theme-switch-current"
else
  mkdir -p "$HOME/.cache"
  echo "$THEME_KEY" > "$HOME/.cache/theme-switch-current"
fi

gum style --foreground 42 --padding "0 2" \
  "Switched to ${TH_NAME:-$THEME_KEY}"
