shell bash
font_family FiraCode Nerd Font
disable_ligatures always
background_opacity 0.85
background_blur 20
mouse_hide_while_typing yes
scrollback_lines 1000000
unfocused_split_opacity 0.7

include current-theme.conf

# Tmux-like keybindings (Prefix: ctrl+a)
enabled_layouts stack,*
map ctrl+a>ctrl+a send_text all \x01
map ctrl+a>c new_tab
map ctrl+a>% launch --location=vsplit --cwd=current
map ctrl+a>@ launch --location=hsplit --cwd=current
map ctrl+a>x close_window
map ctrl+a>z toggle_layout stack
map ctrl+a>, set_window_title

# Navigation
map ctrl+a>h neighboring_window left
map ctrl+a>j neighboring_window down
map ctrl+a>k neighboring_window up
map ctrl+a>l neighboring_window right
map ctrl+a>o next_window
map ctrl+a>p previous_tab
map ctrl+a>n next_tab

# Tabs by index
map ctrl+a>1 goto_tab 1
map ctrl+a>2 goto_tab 2
map ctrl+a>3 goto_tab 3
map ctrl+a>4 goto_tab 4
map ctrl+a>5 goto_tab 5
map ctrl+a>6 goto_tab 6
map ctrl+a>7 goto_tab 7
map ctrl+a>8 goto_tab 8
map ctrl+a>9 goto_tab 9

# Resizing
map ctrl+a>shift+h resize_window narrower 10
map ctrl+a>shift+j resize_window shorter 10
map ctrl+a>shift+k resize_window taller 10
map ctrl+a>shift+l resize_window wider 10
map ctrl+a>e layout_action distribute_sizes
