# Kitty 1337 Revamp
font_family FantasqueSansMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 14.0

background_opacity 0.9
background_blur 32
window_padding_width 10

# Theme (Catppuccin Mocha)
include current-theme.conf

# Image previews
term xterm-kitty
listen_on unix:/tmp/mykitty
allow_remote_control yes

# Tmux passthrough
set allow_passthrough on

# Smooth cursor
cursor_shape beam
cursor_beam_thickness 1.5
cursor_blink_interval -1

# Tab bar
tab_bar_style powerline
tab_powerline_style slanted
active_tab_foreground   #11111b
active_tab_background   #cba6f7
inactive_tab_foreground #cdd6f4
inactive_tab_background #1e1e2e

# Integration
shell_integration enabled
